apiVersion: apps/v1
kind: Deployment
#metadata.name: web-deployment → the label on the outside of the box (so Kubernetes can refer to it)
#Inside the box, you have instructions for how to run your app called web and we need it because pods keep changing
metadata:
  name: web-deployment  
  labels:
    app: web
## about pod    
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        ## about conatiners
    spec:
      containers:
      - name: go-web-app
        image: go-app-ms:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80


